services:
  backend:
    build: ./backend
    container_name: crudpost-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=development

  frontend:
    build: ./frontend
    container_name: crudpost-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/post-frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
